version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: core/server.py
      FLASK_ENV: production
    stdin_open: true # Keep container open for interactive mode
    tty: true # Allocate a pseudo-TTY for bash
